POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Jamie Oliver",
    "title": "Crispy Moroccan carrots",
    "url":"jamieoliverinsivut",
    "likes": 5
}
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "Joku Jokunen",
    "title": "Kuinka opin kutomaan",
    "url":"Jokujokusensivut",
    "likes":"10"
}
